name: CI/CD to ECR + ASG Refresh

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}        
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}    
      ASG_NAME: ${{ secrets.ASG_NAME }}
      IMAGE_URI: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region "$AWS_REGION" \
            | docker login --username AWS --password-stdin "$ECR_REGISTRY"

      - name: Build & push image (amd64)
        run: |
          GIT_SHA="${GITHUB_SHA::7}"
          docker buildx build --platform linux/amd64 \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$GIT_SHA" \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:latest" \
            --push .

      - name: Start ASG instance refresh (rolling)
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "$ASG_NAME" \
            --strategy Rolling
